spring:
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=FALSE
        driver-class-name: org.h2.Driver
    liquibase:
        enabled: false